name: 'Terraform Deploy to Azure'

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6

      # ⚠️ Optional: Debugging - remove after testing
      - name: 'Show secret env keys (debug only)'
        if: always()
        run: |
          echo "Available secrets:"
          env | grep AZURE || echo "No AZURE_* variables found"
      
      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        run: terraform init -upgrade

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan -var-file="k8s.tfvars" -out="main.tfplan"

      - name: 'Upload Plan Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: main-tfplan
          path: main.tfplan

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve "main.tfplan"